#!/usr/bin/bash
set -euo pipefail
cd web
npm run build
cd ..
mkdir -p ./bin
PATH="$PATH:/home/andrei/.local/go/bin" go build -o ./bin/devbox-manager ./cmd/devbox-manager
./bin/devbox-manager service restart
